name: jsonut
version: 0.2.1

# https://dart.dev/tools/pub/pubspec

description: A minimal utility kit for working with JSON in a typesafe manner.
environment:
  sdk: ^3.3.0

repository: https://github.com/matanlurey/jsonut
issue_tracker: https://github.com/matanlurey/jsonut/issues

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  test: ^1.25.2
