# Format: https://dart.dev/tools/pub/pubspec

name: jsonut
description: A minimal utility kit for working with JSON in a typesafe manner.
version: 0.4.0

environment:
  sdk: ^3.3.0

repository: https://github.com/matanlurey/jsonut

dev_dependencies:
  benchmark_harness: ^2.2.2
  checks: ^0.3.0
  coverage: ^1.7.2
  lints: ^3.0.0
  test: ^1.25.2
